### ISSUE TITLE
[discussion] Where should book artifacts persist ?

### ISSUE THREAD

**Issue by emdupre** [neurolibre/roboneuro#10]
In #9 I'm assuming that book artifacts (i.e., the generated HTML) should persist on GitHub. An alternative -- that I can't remember if we explicitly discussed -- is to have them persist on the Production server.

Currently the workflow is something like :

- User builds on Preview page
- Book is generated on Test server and persists for finite period of time

In #9 I'm aiming to extend that workflow to:
- User submits to neurolibre.org
- Editor opens review issue
- In review issue, `roboneuro generate nl-notebook` call triggers a jupyterbook build

Currently that build should take place on the Test server, since those are the only credentials I have access to. Then, the internal workflow proceeds as:

- Test server builds book
- Generated `html` folder copied over to GitHub
- User notified with GitHub link

An alternative would be to call the Production server to build the book from GitHub. This internal workflow would instead look like:

- Production server builds book
- User notified with NeuroLibre server link

Any book that begins the [pre] review process is then assumed to be eventually published -- in which case persisting the contents is correct -- or withdrawn. If the builds will persist on the Production server, then copying them to GitHub is unnecessary, and we can instead directly link them in the RoboNeuro comments.

One downstream possibility this opens up is that we cut a Zenodo release with the archive on the server at time of acceptance, rather than trying to cut a release for a sub-portion of a repo or asking the authors to cut it themselves.

cc @agahkarakuzu @ltetrel @mathieuboudreau @pbellec for comments from https://github.com/neurolibre/neurolibre-reviews/issues/2 experience

**Comment by ltetrel** [comment]
Few comments here on the limitations with the current setup :)

> * User submits to neurolibre.org
> 
> * Editor opens review issue
> 
> * In review issue, `roboneuro generate nl-notebook` call triggers a jupyterbook build

First, some technical details on how the jupyter book is triggered:
The jupyter-book build needs to be executed on the k8s/binderhub cluster because it is where the user environment (docker image) is stored. This process is done "inside" binderhub because from outside there is no actual way to communicate with the cluster. It could be possible to make a separate API on the same server just to trigger the book builds BUT because of how k8s/binderhub mess up the internal network, I am afraid to break anything if installing another API on top of it (trust me, managing a k8s cluster is a "usine à gaz"). That is why the book build is transparent, happening right after a binder build (which also gives me the docker image id related to the repo). It executes the book build [after all checks have been done](https://github.com/neurolibre/terraform-binderhub/blob/c1e47d91ab7405e11076806e48c13759c89786f1/terraform-modules/binderhub/assets/config.yaml#L114-L120) (depending on the repo content).
Then the API check for its artifacts and make it transparent for the outside registered user.

Personally I am more in favor of making things automatic (including jupyter book build), I don't clearly understand why you think it is necessary for an editor to trigger a build. Still if we would like a mechanism like that, I would suggest to leave the process as it is, and then `roboneuro generate nl-notebook` would actually just return the html preview (or any other things we would like). Indeed, user does not need to know that the jupyter book build is actually triggered, but he would be aware of the actual output at this stage. If we are concerned about the re-build with this method, a user needs to push a new commit anyway (if a non-successfull build) and submit after he updated his repo (this triggers a binder build, and a jupyter-book build).

> An alternative would be to call the Production server to build the book from GitHub. This internal workflow would instead look like:
> 
>     * Production server builds book
> 
>     * User notified with NeuroLibre server lin
and
> Currently that build should take place on the Test server, since those are the only credentials I have access to. 

I proposed to leave the production server "free" of jupyter book build few months ago. The cluster is indeed quite unstable at the moment since our new VM stack (opennebula), and the quality of the McGill hardware; adding new mechanism (jupyter book build) to it would just add burden to the server.

**Comment by pbellec** [comment]
This thread covers many topics - I've tried to break down my response into small items. I hope I've covered everything.

**re the build trigger mechanism** I don't mind that the submission manager needs to trigger builds manually. I think this will be useful if users submit revisions of their work. We may want to add a first build automatically to the thread, but it seems like a detail.

**Re test vs production server during review**: I am strongly in favor of building the book on the test server. The testing phase is where we can catch issues regarding the amount of resources required by a book. We want to avoid pushing content that may cause issues on the production server. 

**Re where the artefacts live during review**: The real artefacts include pdf, html, data and environment. The only feasible place for those is the test server (see above). 

**Re where the artefacts live after acceptance**: The real artefacts (pdf | html | data | environment) need to live on the production server - that's where they are served to users. These artefacts are very precious as it may be challenging or even impossible to rebuild. Although this is not set up at the moment, we can add on offsite tape backup with compute canada easily. 

**Re artefacts posted on github**: It looks like the logic of joss is to push artefacts (pdfs) on github - but html builds feature many files and I am concerned that aggregating many html submissions on a github repo is not going to scale. I suggest only hosting the pdf on github - this way we stay close to the joss workflow and we know it will scale. 

**Re doi and external archivals**: The full artefacts may simply be too big for zenodo. Part of the value of neurolibre is to provide long-term storage for both data and environment on a single server - which is what makes the hub fast. My preference at this stage would be to automatically create a zenodo release with the pdf+html. We would have a separate archival, and a DOI. I am in contact with UdeM to discuss using dataverse or other alternatives for this btw, but we could get started with zenodo. 

**re the stability of the production server**: this is extremely concerning, I was not aware of that. The key value proposition of neurolibre is that it is fast and reliable. We need to address any issue with the production server asap. 

**on building html vs building jupyter environments**: they are the same thing!! The html have a link to the binder hub. These links 100% need to be functional. Neurolibre is not a website generator, it is an interactive data plaftorm. If the binder links don't work, the html compilation has failed in a sense. So part of the html build is to cache data, index the docker image, and make sure the link works. 

**on the degree of persistence on test server** The pdf | html | data | environments artefacts need to persist for the duration of the review. A minimum of 48 hours, maybe 72 hours to be on the safe side.

**Comment by ltetrel** [comment]
**Re test vs production server during review**:
Agree also that when we are building for the first time, the user is expected to re-build it in the future and so this can be seen as a test. Also in terms of security, I would be more confident letting ppl push whatever they want on our test server VS prod.

**Re artefacts posted on github** 
Yes! This was also my concern when we decided to store the builds in one repo, how this single git repo will scale after 100 submissions (same if we store pds btw) ??? VS multiple repos or new branch containing the build on the fork of the user's repo. And this second solution has the benefit to encapsulate everything on one single repo which makes maintenance, issue tracking much easier.

**re the unstability of the production server**
@pbellec I am in contact with the admin of cancer computer since few weeks for that, and hope it will be resolved. Unfortunately I cannot resolve them myself since this is entirely due to the OpenNebula stack (and could be also hardware related). But let's not have this conversation here I will contact you.

**Comment by emdupre** [comment]
Thanks both ! Sorry for not more clearly delineating the discussion points; thanks @pbellec for writing those out.

From the discussion above, it sounds like @pbellec you're suggesting that we serve the PDF from GitHub and the HTML from the Test Server for the entire workflow (i.e. even after opening the pre-review and review issues). Since there will be no HTML / notebook content on GitHub, then the question will be how best to directly move the accepted content from the Test to the Production server. RoboNeuro could send a POST request to the Test server to trigger this, as moving it all through Heroku might be less than ideal.

In this case, I'll amend #9 to just serve the link from the test server. I won't update the acceptance mechanism until we have an agreed path forward there.

**Comment by emdupre** [comment]
Resolving based on off-line discussions and moving to workflow outlined in #13 !
