### ISSUE TITLE
RoboNeuro build failed without generating a log

### ISSUE THREAD

**Issue by tsalo** [neurolibre/roboneuro#21]
My recent RoboNeuro submission (https://roboneuro.herokuapp.com/preview?id=4fde2561a01885b60dbcdb14) failed, with the following error:

```
Your preprint build failed to compile with the following errors: 

{}
```

I haven't received an email with the log yet.

This issue comes from https://github.com/neurolibre/neurolibre-binderhub/issues/33.

**Comment by ltetrel** [comment]
FYI, now there are 3 different artifacts from you:
http://neurolibre-data.conp.cloud/book-artifacts/NBCLab/github.com/nimare-paper/b27a087fc3510435807154fff33a438abec8b1f1/_build/html/abstract.html
http://neurolibre-data.conp.cloud/book-artifacts/NBCLab/github.com/nimare-paper/ddb4b020946682e41a46dd61e75f8f32913ed908/_build/html/abstract.html
and
http://neurolibre-data.conp.cloud/book-artifacts/NBCLab/github.com/nimare-paper/7101be5cf602f148ffbc3ece0b87c94bef19a5af/_build/html/abstract.html

**Comment by ltetrel** [comment]
I also just sent a request directly to the cluster (bypassing RoboNeuro) to check if the build is okay.

**Comment by tsalo** [comment]
I believe that those three artifacts are from before `repo2data` was updated. In all three, the code snippets fail because the data files aren't where I specified. Unless they're more recent and I'm still not pointing to the right data directory?

**Comment by ltetrel** [comment]
Still you should have the logs so there is an issue with RoboNeuro logging.
For the repo2data issue we can talk here: https://github.com/neurolibre/neurolibre-binderhub/issues/33

**Comment by tsalo** [comment]
I think this is the issue where I should follow up about the failing build. The data are downloading correctly now, but the build still failed without sending me a log.

**Comment by ltetrel** [comment]
So the issue is regarding the notebook execution (required when `jupyter-book build`) that exceed the 1h default user session timeout.

If you exceed this timeout because notebook execution is too large, you have multiple solution:
1. Use jupyter notebook caching by enabling 
    ```
    execute:
      execute_notebooks: cache
    ```

    You can find more details here: https://jupyterbook.org/content/execute.html#caching-the-notebook-execution.
    Then when you will re-submit (multiple times as necessary, wait few hours between each) the execution will be faster for cached content and you will be able to execute everything within the 1h timeframe.
    
  2. Upload you ipynb checkpoints and use repo2data (another dict in the data_req file) to get the checkpoints inside your env. 
  But just as read-only.

On my side:
* If 1) I will further increase the timeout on the cluster, mostly the number of re-tries. this should help to have everything ready without you re-trying (to much) multiple submissions.
* If 2) This would require important developments on my side that I am not sure how to handle (the `./data` in user env is read-only). So 1) seems to be the fastest solution ATM.

Still the fact that RoboNeuro does properly log back the user is still an issue @agahkarakuzu  @emdupre, the logs are accessible on the server.

**Comment by ltetrel** [comment]
@tsalo just increased the number of re-tries.
If you enable caching you can re-submit (just once please) and it should run for 10*1h during the night!

**Comment by emdupre** [comment]
@ltetrel what are you seeing that the server returns as a code ? I checked the RoboNeuro logs and it's not registering a known error code, just failing on the lack of a provided book_url. Without a set code it's not clear how to set the error message :confused:

**Comment by tsalo** [comment]
@ltetrel I switched to `cache` and resubmitted. 🤞

**Comment by ltetrel** [comment]
I did not trigger the API, I am using the good-old binderhub website to resolve faster this issue.

The book log is accessible at: http://neurolibre-data.conp.cloud/book-artifacts/NBCLab/github.com/nimare-paper/39c5deb8de19d845b79557d25276c55b8bd03ec5/book-build.log
What @agahkarakuzu put in place was to send this file to the user if it fails, also the binder build log (that I am also sending back after a binder build request), but apparently @tsalo did not receive anything?

**Comment by ltetrel** [comment]
Perfect @tsalo, this will take time then and we cross fingers for tomorrow!

**Comment by ltetrel** [comment]
re-logs, @tsalo have you checked your spam folder just in case ?

**Comment by tsalo** [comment]
@ltetrel no logs in my spam folder either. Just the initial email about the submission.

**Comment by ltetrel** [comment]
> @ltetrel no logs in my spam folder either. Just the initial email about the submission.

Hummm could it be because of the submission was more than 1h (reaching RoboNeuro timeout)? I don't know what to say at this stage, just that the API returns two codes and when I `curl` the API directly I have either one of these two outputs: https://github.com/neurolibre/neurolibre-data-api/blob/0cff7acaed3a961493a0795bc9b1d113414ec7dc/neurolibre-data-api/neurolibre-data-api.py#L139-L154

**Comment by ltetrel** [comment]
So it is still failing (not finishing executing notebooks) after 10x1 hours. I investigate and saw that on hpc you are using 8 cpus: https://github.com/NBCLab/nimare-paper/blob/19ed56e79c21309eb2598112ee02c4343565945d/fiu-hpc/build_book.sbatch#L1-L3
Unfortunately user has access just to 1cpu on the test server, so I imagine running your entire workflow would not be 8hours, but at least 3 times more.

I also saw that you pushed your `_build` folder to github, pushing artifacts is not recommended because it will make the docker env bigger, and results in slower overall performance. In your case since it is not too big I don't think this will have a huge impact, so we could use this `_build` and say to jupyter-book to use your cache dir here (instead of remaking a new one which takes insanely long): https://github.com/NBCLab/nimare-paper/tree/master/content/_build/.jupyter_cache
wdyt @tsalo do you confirm that the cache on your github repo can be re-used?

**Comment by tsalo** [comment]
>I investigate and saw that on hpc you are using 8 cpus

That's true, but the only step that should currently be using more than one is the multiple comparisons correction one, which is using four. I can drop that down to one. I don't think it would affect the build speed too much.

>I also saw that you pushed your _build folder to github, pushing artifacts is not recommended because it will make the docker env bigger, and results in slower overall performance.

I was doing this so that I could check the builds on https://nbclab.github.io/nimare-paper, but I can remove the build files. Just to clarify, I would remove everything in `_build` _except_ `_build/.jupyter_cache/`?

**Comment by ltetrel** [comment]
> I was doing this so that I could check the builds on https://nbclab.github.io/nimare-paper, but I can remove the build files. Just to clarify, I would remove everything in `_build` _except_ `_build/.jupyter_cache/`?

No don't remove it since you have a github page that uses them, I check the size it is around 30MB so that is okay.
Just add the cache path to the jupyter-book config file:
```execute:
  cache: path/to/mycache
```

**Comment by ltetrel** [comment]
> That's true, but the only step that should currently be using more than one is the multiple comparisons correction one, which is using four. I can drop that down to one. I don't think it would affect the build speed too much.

Also don't remove that one, since we will be using the pre-generated cache anyway

**Comment by tsalo** [comment]
Okay, I specified the cache location, but it's the same as the default location, so I don't know if that will have any effect. Should I rebuild on the HPC before submitting to RoboNeuro again?

**Comment by ltetrel** [comment]
No it is not the same because on Neurolibre the output is written on another directory mounted on the repo, and you don't have any cache there (on the backend). So basically what it will do is when running the jupyter book, it will read the cache from your github repo, and write the output to the Neurolibre backend.

So there is nothing else to do apart of changing the `cache` path, just make sure that this cache that you have on github can be re-used with the current version (so yes if needed re-run on your HPC).

**Comment by tsalo** [comment]
That makes sense. I'll re-run on my HPC so the cache goes to the right place and resubmit to RoboNeuro once that's done.

**Comment by ltetrel** [comment]
> That makes sense. I'll re-run on my HPC so the cache goes to the right place and resubmit to RoboNeuro once that's done.

Push to github the cache after re-running, and then submit with RoboNeuro.

Overall Neurolibre is not really meant for such long-time execution, but we should be able to handle it if cache is properly loaded.
:D

**Comment by ltetrel** [comment]
```Running Jupyter-Book v0.11.3

MyST NB Configuration Error:
'jupyter_cache' is not a directory: _build/.jupyter_cache
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_book/sphinx.py", line 128, in build_sphinx
    keep_going=keep_going,
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/sphinx/application.py", line 269, in __init__
    self.events.emit('config-inited', self.config)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/sphinx/events.py", line 111, in emit
    results.append(listener.handler(self.app, *args))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/myst_nb/__init__.py", line 202, in validate_config_values
    f"'jupyter_cache' is not a directory: {app.config['jupyter_cache']}",
myst_nb.MystNbConfigError: 'jupyter_cache' is not a directory: _build/.jupyter_cache
```
Was it working locally for you ? I think you forgot to point to `content` dir (`content/_build/.jupyter_cache`).

**Comment by tsalo** [comment]
I didn't realize it was built from the main directory and not content on RoboNeuro's side. That makes sense though. I can change it.

**Comment by tsalo** [comment]
Changing the cache location worked!!

**Comment by tsalo** [comment]
I guess I can close this and start the official submission process, right?

**Comment by ltetrel** [comment]
So originally the issue was for RoboNeuro not logging you the error (I had to manually send you these logs), so this issue is not resolved!
For the submission itself yes go ahead.

**Comment by emdupre** [comment]
@ltetrel just confirming, it seemed like you wanted @agahkarakuzu specifically to weigh in here, so I'm not looking into this at present.

**Comment by ltetrel** [comment]
> @ltetrel just confirming, it seemed like you wanted @agahkarakuzu specifically to weigh in here, so I'm not looking into this at present.

Yes indeed, I just wanted to confirm with him the mechanism to send back the jupyter-book and binder build logs.

**Comment by agahkarakuzu** [comment]
The logs have been improved. For reference: https://github.com/neurolibre/neurolibre-reviews/issues/4#issuecomment-1098366340
